repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
        exclude: \.ambr$
      - id: trailing-whitespace
        exclude: \.ambr$
      - id: mixed-line-ending
        exclude: \.ambr$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.13
    hooks:
      - id: ruff
      - id: ruff-format
